# Generated by Django 4.2 on 2026-03-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actor_expense_project_scene_schedule_delete_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='actors',
        ),
    ]
