# Generated by Django 4.2 on 2026-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_schedule_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='actors',
            field=models.ManyToManyField(to='app.actor'),
        ),
        migrations.AddField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
