# Generated by Django 4.2 on 2026-03-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_scene_actors_scene_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='scripts/'),
        ),
    ]
