# Generated by Django 6.0.3 on 2026-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('production_manager', 'Production Manager'), ('viewer', 'Viewer')], default='viewer', max_length=25),
        ),
    ]
