# Generated by Django 6.0.5 on 2026-05-07 07:29

from django.db import migrations, models
import django.db.utils

class SafeAddField(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except django.db.utils.OperationalError as e:
            error_str = str(e).lower()
            if "duplicate column name" in error_str or "already exists" in error_str or getattr(e, 'args', [0])[0] in (1060,):
                pass
            else:
                raise

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userprofile_role'),
    ]

    operations = [
        SafeAddField(
            model_name='project',
            name='cinematography',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        SafeAddField(
            model_name='project',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        SafeAddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        SafeAddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        SafeAddField(
            model_name='project',
            name='music_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        SafeAddField(
            model_name='project',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        SafeAddField(
            model_name='project',
            name='running_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        SafeAddField(
            model_name='project',
            name='written_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
